meta_product_name: "CHOY"
meta_title: "CHOY - The new mobile fashion app"
meta_description: "Simple shopping experience through easy descisions"
meta_image: "LogoRec.png" # should exist in `app/assets/images/`
